# Generated by Django 5.2.4 on 2025-09-19 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_delete_resume'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_resumes', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='resume_files',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
